---

- name: import grafana gpg signing key
  apt_key: url=https://packages.grafana.com/gpg.key state=present

- name: setup grafana repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb {{ deb_dist }} {{ deb_component }}"
    state: present

- name: install grafana
  apt: name=grafana state=present

- name: set admin password
  lineinfile:
    dest: /etc/grafana/grafana.ini
    regexp: ';admin_password = admin'
    line: "admin_password = {{ grafana_password_vault }}"
  register: admin_pwd

- name: start grafana-server
  service:
    name: grafana-server
    state: restarted
    enabled: yes
  when: admin_pwd.changed
