---

- name: ensure data directory
  file:
    path: "{{ vaultwarden_path }}/var/lib/vaultwarden"
    state: directory

- name: Pull default Docker image
  docker_image:
    name: "{{ vaultwarden_image }}:{{ vaultwarden_version }}"
    source: pull

- name: Run vault-warden Container
  docker_container:
    name: vaultwarden-server
    image: "{{ vaultwarden_image }}:{{ vaultwarden_version }}"
    state: started
    network_mode: host
    volumes:
      - "{{ vaultwarden_path }}/var/lib/vaultwarden/:/data/"
    container_default_behavior: "no_defaults"
    env:
      ADMIN_TOKEN: "{{ vaultwarden_password }}"
      DOMAIN: "https://pm.{{ base_domain }}"
      SIGNUPS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
      ROCKET_PORT: "4000"
      ROCKET_ADDRESS: "127.0.0.1"
